- name: set registry dns
  lineinfile:
    path: "/etc/dnsmasq.d/fit2openshift.dns.conf"
    regexp: 'address=/registry.fit2openshift.io/'
    line: "address=/registry.fit2openshift.io/{{local_hostname}}"

