---

- name: distribute ssh key to node
  hosts: OSEv3
  tasks:
    - name: copy ssh key to node
      gather_facts: false
      authorized_key:
        user: root
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
        state: present
        exclusive: no
