name: okd-3.11
version: 3.11
install_playbooks:
  - name: 1-prepaire
    alias: prepare.yml
  - name: 2-run-prequisites
    alias: openshift-ansible/playbooks/prerequisites.yml
  - name: 3-deploy-cluster
    alias: openshift-ansible/playbooks/deploy_cluster.yml
upgrade_playbooks: upgrade.yml
configs:
  - name: openshift_master_cluster_hostname
    alias: 域名
    type: Input
    default: master.fit2openshift.com
    required: true
    help_text: 访问的fit2openshift的域名

  - name: openshift_master_default_subdomain
    alias: 子域名后缀
    type: Input
    default: apps.test.example.com
    required: true
    help_text: 部署app后service的域名


# template public roles
roles:
  - name: etcd
    children:
      - masters
    meta:
      hidden: true
  - name: OSEv3
    children:
      - masters
      - nodes
      - etcd
    meta:
      hidden: true
    vars:
      ansible_ssh_user: root
      ansible_become: false
      deployment_type: origin
      openshift_deployment_type: origin
      
      openshift_release: 3.11
      openshift_image_tag: v3.11
      enable_excluders: false
      enable_docker_excluder: false
      containerized: true
      
      oreg_url: registry.fit2openshift.io:8082/openshift/origin-${component}:${version}
      system_images_registry: registry.fit2openshift.io:8082
      openshift_docker_additional_registries: registry.fit2openshift.io:8082
      openshift_service_catalog_image_prefix: registry.fit2openshift.io:8082/openshift/origin-
      openshift_metrics_image_prefix: registry.fit2openshift.io:8082/openshift/origin-
      openshift_logging_image_prefix: registry.fit2openshift.io:8082/openshift/origin-
      ansible_service_broker_image_prefix: registry.fit2openshift.io:8082/openshift/origin-
      ansible_service_broker_etcd_image_prefix: registry.fit2openshift.io:8082/openshift/origin-
      
      openshift_disable_check: disk_availability,docker_storage,memory_availability,docker_image_availability
      
      openshift_clock_enabled: true
      
      openshift_rolling_restart_mode: system
      
      openshift_docker_disable_push_dockerhub: true
      openshift_docker_options: "--log-driver=journald --log-level=warn --ipv6=false --insecure-registry=0.0.0.0/0 --registry-mirror=https://docker.mirrors.ustc.edu.cn"
      openshift_docker_insecure_registries: docker-registry.default.svc,docker-registry.default.svc.cluster.local,registory.fit2openshift.io:8082
      
      
      openshift_master_api_port: 8443
      openshift_master_console_port: 8443
      
      openshift_master_cluster_method: native
      
      os_sdn_network_plugin_name: redhat/openshift-ovs-multitenant
      
      osm_cluster_network_cidr: 10.100.0.0/16
      openshift_portal_net: 172.30.0.0/16
      osm_host_subnet_length: 8
      
      openshift_generate_no_proxy_hosts: true
      
      openshift_master_identity_providers:[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]
      
      openshift_master_overwrite_named_certificates: true
      openshift_metrics_install_metrics: false
      openshift_logging_install_logging: false
      openshift_cluster_monitoring_operator_install: false
      openshift_enable_service_catalog: false
      installer_ip: registry.fit2openshift.io



templates:
  - name: 单节点
    roles:
      - name: masters
        vars:
          openshift_node_group_name: node-config-all-in-one
        meta:
          hidden: false
          nodes_require:
            - '='
            - 1
      - name: nodes
        children:
          - masters
        meta:
          hidden: true

  - name: 一主多节点
    roles:
      - name: masters
        vars:
          openshift_node_group_name: node-config-master-infra
        meta:
          hidden: false
          nodes_require:
            - '='
            - 1
      - name: cumpute
        meta:
          hidden: false
          nodes_require:
            - '>'
            - 2
      - name: nodes
        children:
          - masters
          - compute
        meta:
          hidden: true

