- name: check if selinux is running and enforced
  command: getenforce
  register: sestatus
  changed_when: false
- name: enable selinux config
  replace: 'path=/etc/selinux/config regexp="SELINUX=disabled" replace="SELINUX=enforcing" backup=yes'
  when: sestatus.stdout == "Disabled"
- name: reboot system
  command: reboot
  when: sestatus.stdout == "Disabled"
- name: Wait for host to start
  local_action:
    module: wait_for
    port: 22
    delay: 5
    timeout: 300
#- wait_for: port=22 state=started
#  wait_for: port=22 state=started
#- debug: msg="status is {{selinux_status}}"
#  command: sed -i 's/SELINUX=disabled/SELINUX=enforcing/g' /etc/selinux/config
#  when: selinux_status.stdout == "Disabled"

