- name: check host in DNS
  shell: cat /opt/fit2openshift/conf/dnsmasq/dnsmasq.d/{{cluster_name}}.dns.conf | grep {{ansible_ssh_host}}
  register: host_in_dns
  delegate_to: localhost
  delegate_facts: False
  failed_when: false
  changed_when: true

- name: debug host in dns return
  debug: 
    msg: "{{host_in_dns.rc}}"

- name: add DNS
  lineinfile:
    path: "/opt/fit2openshift/conf/dnsmasq/dnsmasq.d/{{cluster_name}}.dns.conf"
    line: "address=/{{inventory_hostname}}/{{ansible_ssh_host}}"
  delegate_to: localhost
  delegate_facts: False
  when: host_in_dns.rc != 0
