- hosts: all_nodes
  roles:
    - ssh
    - repository
    - firewall
- hosts: master
  roles:
    - daemon
- hosts: cluster_nodes
  roles:
    - host-dns
    - rpm
    - ntp

- hosts: localhost
  roles:
    - localhost

