- hosts: all_nodes
  roles:
    - ssh
    - repository
    - firewall
- hosts: master
  roles:
    - daemon
- hosts: cluster_nodes
  roles:
    - host-dns
    - rpm

- hosts: kube-node
  roles:
    - ntp

- hosts: localhost
  roles:
    - localhost

