# download bin
- name: prepare kube bin files
  hosts: localhost
  connection: local
  roles:
    - kube-bin

# to create CA, kubeconfig, kube-proxy.kubeconfig etc. on 'deploy' node
- hosts: "{{groups['kube-master'][0]}}"
  roles:
    - deploy

# prepare tasks for all nodes
- hosts:
    - kube-master
    - kube-node
    - deploy
  roles:
    - prepare

# to install etcd cluster
- hosts: etcd
  roles:
    - etcd

- hosts: kube-node
  roles:
    - docker