- hosts: "{{groups['new_node'][0]}}"
  tasks:
    - name: drain node
      shell: "kubectl drain {{item}} --delete-local-data --force --ignore-daemonsets"
      with_items: "{{groups['new_node']}}"

    - name: remove node
      shell: "kubectl delete node {{item}}"
      with_items: "{{groups['new_node']}}"
