- name: prepare kube bin files
  hosts: localhost
  connection: local
  roles:
    - kube-bin

- hosts: master
  roles:
    - daemon

- hosts: new_node
  roles:
    - ssh
    - repository
    - firewall
    - prepare
    - host-dns
    - rpm
    - ntp
    - docker
    - { role: kube-node, when: "DEPLOY_MODE != 'allinone'" }
    - { role: flannel, when: "CLUSTER_NETWORK == 'flannel'" }
    - { role: calico, when: "CLUSTER_NETWORK == 'calico'" }
    - scale
