---
- name: Generate serviceaccount config file
  template:
    src: nfs_serviceaccount.yml.j2
    dest: "{{ temp.stdout }}/nfs_serviceaccount.yml"

- name: Create serviceaccount resource
  oc_obj:
    namespace: "{{ current_namespace }}"
    kind: ServiceAccount
    name: 'nfs-client-provisioner'
    state: present
    files:
    - "{{temp.stdout}}/nfs_serviceaccount.yml"

- name: Generate ClusterRole config file
  template:
    src: nfs_cluster_role.yml.j2
    dest: "{{ temp.stdout }}/nfs_cluster_role.yml"

- name: Create clusterRole resource
  oc_obj:
   namespace: "{{ current_namespace }}"
   kind: ClusterRole
   name: 'nfs-client-provisioner-runner'
   state: present
   files:
   - "{{temp.stdout}}/nfs_cluster_role.yml"

- name: Generate ClusterRoleBinding config file
  template:
    src: nfs_cluster_role_binding.yml.j2
    dest: "{{ temp.stdout }}/nfs_cluster_role_binding.yml"

- name: Create clusterRoleBinding resource
  oc_obj:
    namespace: "{{ current_namespace }}"
    kind: ClusterRoleBinding
    name: 'run-nfs-client-provisioner'
    state: present
    files:
    - "{{temp.stdout}}/nfs_cluster_role_binding.yml"

- name: Generate Role config file
  template:
    src: nfs_role.yml.j2
    dest: "{{ temp.stdout }}/nfs_role.yml"

- name: Create Role resource
  oc_obj:
    namespace: "{{ current_namespace }}"
    kind: Role
    name: 'leader-locking-nfs-client-provisioner'
    state: present
    files:
    - "{{temp.stdout}}/nfs_role.yml"

- name: Generate RoleBinding config file
  template:
    src: nfs_role_binding.yml.j2
    dest: "{{temp.stdout}}/nfs_role_binding.yml"

- name: Create RoleBinding resource
  oc_obj:
    namespace: "{{ current_namespace }}"
    kind: RoleBinding
    name: 'leader-locking-nfs-client-provisioner'
    state: present
    files:
    - "{{temp.stdout}}/nfs_role_binding.yml"
- name: Add Cluster Role to serviceaccount
  oc_adm_policy_user:
    user: "system:serviceaccount:{{ current_namespace }}:nfs-client-provisioner"
    resource_kind: scc
    resource_name: hostmount-anyuid
    state: present