---
- name: Create nfs storage class
  template:
   src: nfs_storage_class.yml.j2
   dest: '{{temp.stdout}}/nfs_storage_class.yml'

- name: Deploy nfs storage class
  oc_obj:
    namespace: "{{ current_namespace }}"
    name: nfs-storage
    kind: StorageClass
    state: present
    files:
     - "{{temp.stdout}}/nfs_storage_class.yml