---
- name: Generate deployment config file
  template:
    src: nfs_deployment.yml.j2
    dest: "{{ temp.stdout }}/nfs_deployment.yml"

- name: Deployment nfs storage provisioner
  oc_obj:
    namespace: "{{ current_namespace }}"
    kind: deployment
    state: present
    name: nfs-client-provisioner
    files:
    - "{{temp.stdout}}/nfs_deployment.yml"

- name: Wait for deploy nfs storage provisioner
  oc_obj:
    namespace: "{{ current_namespace }}"
    kind: pod
    state: list
    selector: 'app=nfs-client-provisioner'
  register: deploy_nfs_storage_provisioner
- debug:
    msg: "{{ deploy_nfs_storage_provisioner }}"
  until:
  - "deploy_nfs_storage_provisioner.results.results[0]['items'] | count >0"
  - "deploy_nfs_storage_provisioner.results.results[0]['items'] | lib_utils_oo_collect(attribute='status.conditions') | lib_utils_oo_collect(attribute='status', filters={'type': 'Ready'}) | map('bool') | select | list | count == 1"
  delay: 10
  retries: "{{ (nfs_storage_timeout | int / 10) | int }}"