version: "2.2"
services:
  nginx:
    image: nginx:alpine
    container_name: jms_nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - api_data:/data
      - ${VOLUME_DIR}/nginx/log:/var/log/nginx
      - ./nginx/http_server.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - ui
    healthcheck:
      test: ["CMD", "test", "-f", "/var/run/nginx.pid"]
      interval: 10s
      timeout: 5s
      retries: 2

  api:
    build: api
    container_name: f2o_api
    ports:
      - 8080:8080
    restart: always
    privileged: true
    tty: true
    volumes:
      - api_data:/opt/fit2openshift/data
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: SuMk2lH20ocmvyu1p38m40
      DB_NAME: fit2openshift

  mysql:
    container_name: f2o_mysql
    image: mysql:5.7.24
    command: --character-set-server=utf8
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: fit2openshift
      MYSQL_ROOT_PASSWORD: SuMk2lH20ocmvyu1p38m40

  redis:
    image: redis:alpine
    container_name: f2o_redis
    restart: always
    volumes:
      - redis_data:/data
    command: ["redis-server", "/etc/redis.conf"]
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$$REDIS_PASSWORD", "info"]
      interval: 10s
      timeout: 5s
      retries: 10

  nexus:
    container_name: f2o_nexus
    image: sonatype/nexus3
    ports:
      - 8081:8081
      - 8082:8082
    volumes:
      - ./nexus/data:/nexus-data

  dnsmasq:
    container_name: f2o_dnsmasq
    image: jpillora/dnsmasq:latest
    volumes:
      - /opt/fit2openshift/conf/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
      - /opt/fit2openshift/conf/dnsmasq/dnsmasq.d:/etc/dnsmasq.d
    networks:
      - fit2openshift-network
    ports:
      - 5380:8080/tcp
      - 53:53/udp
    environment:
      HTTP_USER: admin
      HTTP_PASS: admin123

volumes:
  api_data:
  mysql_data:
  redis_data:

networks: 
  default:
