version: "2.2"
services:
  nginx:
    image: nginx:alpine
    container_name: f2o_nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - api_data:/data
      - ./docker/nginx/f2o.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - ui
    healthcheck:
      test: ["CMD", "test", "-f", "/var/run/nginx.pid"]
      interval: 10s
      timeout: 5s
      retries: 2

  api:
    build: api
    container_name: f2o_api
    restart: always
    privileged: true
    tty: true
    volumes:
      - api_data:/opt/fit2openshift/data
      - dnsmasq_data:/etc/dnsmasq.d
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: SuMk2lH20ocmvyu1p38m40
      DB_NAME: fit2openshift
      REDIS_HOST: redis
    depends_on:
      - mysql
      - redis

  mysql:
    container_name: f2o_mysql
    image: mysql:5.7.24
    command: --character-set-server=utf8
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: fit2openshift
      MYSQL_ROOT_PASSWORD: SuMk2lH20ocmvyu1p38m40
    healthcheck:
      test: "mysql -uroot -h127.0.0.1 -pSuMk2lH20ocmvyu1p38m40 -e 'SHOW DATABASES;'"
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:alpine
    container_name: f2o_redis
    restart: always
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "info"]
      interval: 10s
      timeout: 5s
      retries: 10

  ui:
    build: ui
    container_name: f2o_ui
    restart: always

  nexus:
    container_name: f2o_nexus
    image: sonatype/nexus3
    ports:
      - 8081:8081
      - 8082:8082
    volumes:
      - ./docker/nexus/data:/nexus-data

  dns:
    container_name: f2o_dnsmasq
    build: docker/dns
    volumes:
      - dns_data:/etc/dnsmasq.d
    ports:
      - 53:53/udp

volumes:
  api_data:
  mysql_data:
  redis_data:
  dns_data:

networks: 
  default:
