version: "2"
services:
  fit2openshift:
    image: registry.fit2cloud.com/fit2anything/fit2openshift/fit2openshift-app:latest
    container_name: fit2openshift-app
    ports:
      - 80:80
      - 8080:8080
    networks:
      - fit2openshift-network
    restart: always
    tty: true
    volumes:
      - host_logging-data:/opt/fit2openshift-app/data/log
      - /opt/fit2openshift/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - share-volumes:/opt/fit2openshift-app/data/packages
      - /opt/fit2openshift/conf/ssh/config:/root/.ssh/config
      - /opt/fit2openshift/conf/fit2openshift/fit2openshift_conf.yml:/opt/fit2openshift/conf/fit2openshift/fit2openshift_conf.yml
  fit2openshift-db:
    container_name: fit2openshift-db
    image: mysql:5.7.24
    env_file:
      - /opt/fit2openshift/conf/mysql/mysql.env
    ports:
      - 3306:3306
    volumes:
      - /opt/fit2openshift/conf/mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - /opt/fit2openshift/conf/mysql/bin:/docker-entrypoint-initdb.d/
      - host-opt-fit2openshift-mysql-data:/var/lib/mysql
    networks:
      - fit2openshift-network
  okd-3.11_offline:
    container_name: okd-3.11_offline
    image: registry.fit2cloud.com/fit2anything/fit2openshift/okd_offline_package:v3.11.0-0cbc58b
    volumes:
      - share-volumes:/opt/fit2openshift/offline_packages
    networks:
      - fit2openshift-network
  nexus-registry:
    container_name: nexus-registry
    image: sonatype/nexus3
    ports:
      - 8081:8081
      - 8082:8082
    networks:
      - fit2openshift-network
    volumes:
      - nexus-data:/nexus-data
      
volumes:
  share-volumes:
  host-opt-fit2openshift-mysql-data:
    driver_opts:
      type: none
      device: /opt/fit2openshift/data/mysql
      o: bind
  host_logging-data:
    driver_opts:
      type: none
      device: /opt/fit2openshift/logs/runtime
      o: bind
  nexus-data:
    driver_opts:
      type: none
      device: /opt/fit2openshift/data/nexus
      o: bind

networks: 
  fit2openshift-network:
