- name: Backup original repos
  shell: mkdir -p /etc/yum.repos.d/backup && /bin/mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/backup  >>/dev/null 2>&1

- name: Create proxy repo 
  template:
    src: templates/fit2openshift.repo.j2
    dest: /etc/yum.repos.d/fit2openshift.repo

