# [optional] to synchronize time of nodes with 'chrony'
- hosts: all_nodes
  roles:
    - role: chrony

# to create CA, kubeconfig, kube-proxy.kubeconfig etc. on 'deploy' node
- hosts: "{{groups['kube-master'][0]}}"
  roles:
    - deploy

# prepare tasks for all nodes
- hosts:
    - kube-master
    - kube-node
    - deploy
    - etcd
    - lb
  roles:
    - prepare

# [optional] to install loadbalance service, only needed by multi-master cluster
- hosts: lb
  roles:
    - lb

# to install etcd cluster
- hosts: etcd
  roles:
    - etcd



# to set up 'kube-master' nodes
- hosts: kube-master
  roles:
    - kube-master
    - kube-node
  # 
  tasks:
    - name: Making master nodes SchedulingDisabled
      shell: "{{ bin_dir }}/kubectl cordon {{ inventory_hostname }} "
      delegate_to: "{{ groups['kube-master'][0] }}"
      when: DEPLOY_MODE != "allinone"
      ignore_errors: true

    - name: Setting master role name
      shell: "{{ bin_dir }}/kubectl label node {{ inventory_hostname }} kubernetes.io/role=master --overwrite"
      ignore_errors: true
      delegate_to: "{{ groups['kube-master'][0] }}"

# to set up 'kube-node' nodes
- hosts: kube-node
  roles:
    - { role: kube-node, when: "DEPLOY_MODE != 'allinone'" }

# to install network plugin, only one can be choosen
- hosts:
    - kube-master
    - kube-node
  roles:
    - { role: calico, when: "CLUSTER_NETWORK == 'calico'" }
    - { role: cilium, when: "CLUSTER_NETWORK == 'cilium'" }
    - { role: flannel, when: "CLUSTER_NETWORK == 'flannel'" }
    - { role: kube-router, when: "CLUSTER_NETWORK == 'kube-router'" }
    - { role: kube-ovn, when: "CLUSTER_NETWORK == 'kube-ovn'" }

# to install storage_class
- hosts: "{{groups['kube-master'][0]}}"
  roles:
    - cluster-storage

# to install helm
- hosts: "{{groups['kube-master'][0]}}"
  roles:
    - helm

# to install cluster-addons
- hosts:
    - cluster_nodes
  roles:
    - cluster-addon

- hosts: "{{groups['kube-master'][0]}}"
  roles:
    - registry

- hosts: "cluster_nodes"
  tasks:
    - name: 尝试登陆 registry
      shell: "docker login {{MASTER_IP}}:30003 -u {{REGISTRY_ACCOUNT_NAME}} -p {{REGISTRY_ACCOUNT_PASSWORD}}"
      register: login_result
      until: login_result.rc == 0
      retries: 40
      delay: 30

- hosts: "{{groups['kube-master'][0]}}"
  roles:
    - dbaas