name: nfs
roles: []
vars:
  storage_nfs_enabled: true
  storage_nfs_storage_class: nfs-dynamic-class
  storage_nfs_provisioner_name: nfs-provisioner
options:
  - name: storage_nfs_server
    comment: nfs_server
    placeholder: 10.0.0.1
    type: text
  - name: storage_nfs__server_path
    comment: nfs_path
    placeholder: /exports
    type: text
