name: netapp
roles: []
vars:
  - name: openshift_storage_netapp_namespace
    value: netapp-storage
options:
  - name: openshift_storage_netapp_driver_name
    comment: driver_name
    default: ontap-nas
    type: text
  - name: openshift_storage_netapp_managementLTF
    comment: managementLTF
    default: 10.0.0.1
    type: text
  - name: openshift_storage_netapp_dataLTF
    comment: dataLTF
    default: 10.0.0.2
    type: text
  - name: openshift_storage_netapp_username
    comment: username
    default: admin
    type: text
  - name: openshift_storage_netapp_password
    comment: password
    default: passwrod
    type: password
