- name: 添加父级解析记录
  lineinfile:
    path: /etc/dnsmasq.d/kubeops.dns.conf
    regexp: 'server=/{{cluster_name}}.{{domain_suffix}}'
    line: 'server=/{{cluster_name}}.{{domain_suffix}}/{{ hostvars[item]["ansible_ssh_host"]}}'
  with_items: "groups['master']"

- name: 重启生效dnsmasq
  service:
    name: dnsmasq
    state: restarted