- name: 添加父级解析记录
  lineinfile:
    path: /etc/dnsmasq.d/kubeops.dns.conf
    regexp: 'server=/{{cluster_name}}.{{domain_suffix}}'
    line: 'server=/{{cluster_name}}.{{domain_suffix}}/{{ hostvars[groups["daemon"][0]]["ansible_ssh_host"]}}'

- name: 重启生效dnsmasq
  service:
    name: dnsmasq
    state: restarted



