name: OpenStack
region:
  vars:
    provider: openstack
    image_vmdk_path: "/images/kubeoperator_centos_7.6.1810/kubeoperator_centos_7.6.1810-1.qcow2"
    image_name: "kubeoperator_centos_7.6.1810"
plan:
  infra:
    - name: k8s_master_model
      alias: Master 规格
    - name: k8s_worker_model
      alias: Worker 规格
    - name: k8s_daemon_model
      alias: Daemon 规格




