resource: kubernetes
version: 1.13.5
playbooks:
  - name: host-check
    alias: common/00_host_check.yml
  - name: send-ssh-key
    alias: common/01_send_ssh_key.yml
  - name: config-ssh
    alias: common/02_config_ssh.yml
  - name: config-dns
    alias: common/03_config_dns.yml
  - name: prepare-host
    alias: common/04_prepare_host.yml
  - name: install-rpms
    alias: common/05_install_basic_rpms.yml
  - name:  config-docker-storage
    alias: common/06_config_docker.yml
  - name:  config-ntp
    alias: common/07_config_ntp.yml
  - name:  install-k8s
    alias: kubeasz/90.setup.yml
roles:
  - name: cluster_nodes
    children:
      - masters
      - compute
      - infra
  - name: all_nodes
    children:
      - lb
      - cluster_nodes
  - name: kube-node
    children:
      - compute
      - infra
  - name: kube-master
    children:
      - masters
  - name: etcd
    children:
      - masters
    meta:
      hidden: true
  - name: kubeasz
    children:
      - masters
      - nodes
      - compute
      - infra
      - lb
    meta:
      hidden: true
    vars:
      MASTER_IP: "{{ groups['lb'][0] }"
      CONTAINER_RUNTIME: "docker"
      CLUSTER_NETWORK: "flannel"
      SERVICE_CIDR: "10.68.0.0/16"
      CLUSTER_CIDR: "172.20.0.0/16"
      NODE_PORT_RANGE: "20000-40000"
      CLUSTER_KUBERNETES_SVC_IP: "10.68.0.1"
      CLUSTER_DNS_SVC_IP: "10.68.0.2"
      CLUSTER_DNS_DOMAIN: "cluster.local."
      KUBE_APISERVER: "https://{{ MASTER_IP }}:8443"
      #kubeOperator
      download_bin_url: "http://registry.fit2openshift.io:8081/repository/k8s-basic-package/1.13.5/k8s.1-13-5.tar.gz"
      file_name: "k8s.1-13-5.tar.gz"
      base_dir: "/opt/kubeOperator-kube-bin/1.13.5"
      #dns
      dns_install: "yes"
      dns_image: "coredns/coredns"
      dns_version: "1.5.0"
      #metrics-server
      metricsserver_install: "yes"
      metricsserver_image: "mirrorgooglecontainers/metrics-server-amd64"
      metricsserver_version: "v0.3.2"
      #dashboard
      dashboard_install: "yes"
      dashboard_image: "mirrorgooglecontainers/kubernetes-dashboard-amd6"
      dashboard_version: "v1.10.1"
      #heapster
      heapster_install: "yes"
      heapster_version: "v1.5.4"
      heapster_image: "mirrorgooglecontainers/heapster-amd64"
      #metallb
      metallb_install: "no"

templates:
  - name: all-in-one 模型
    comment: '此部署模型至少需要主机 1 台，磁盘 2 块，仅用于测试环境，仅安装 kubernetes 核心组件'
    operations:
      - name: install
        display: true
        comment: '安装'
        playbooks:
          - host-check
    #          - send-ssh-key
    #          - config-ssh
    #          - config-dns
    #          - prepare-host
    #          - install-rpms
    #          - config-docker-storage
    #          - config-ntp
    #          - install-k8s
    private_vars:
      DEPLOY_MODE: 'allinone'
    roles:
      - name: masters
        vars:
        meta:
          hidden: false
          allow_os:
            - name: CentOS
              version:
                - "7.4"
                - "7.5"
          node_vars:
            - name: "docker_storage_device"
              verbose: "Docker 存储卷"
              comment: "请选择空白块存储设备，注意此操作将抹除所有数据!"
              type: "Select"
              require: true
          requires:
            nodes_require:
              - '='
              - 1
            volumes_require:
              - name: "system"
                verbose: "系统卷:"
                minimal: 50
                excellent: 100
                comment: "系统卷，用于运行操作系统"
                unit: "GB"
              - name: "data"
                verbose: "数据卷:"
                minimal: 100
                excellent: 500
                comment: "数据卷,用于存储docker数据"
                unit: "GB"
            device_require:
              - name: "cpu_core"
                verbose: "CPU 核心数"
                minimal: 4
                excellent: 8
                comment: "无"
                unit: "个"
              - name: "memory_size"
                verbose: "内存大小"
                minimal: 8
                excellent: 16
                unit: "GB"
                comment: "无"
      - name: compute
        children:
          - masters
        meta:
          hidden: true
      - name: infra
        children:
          - masters
        meta:
          hidden: true


