name: Vshpere
region:
  vars:
    provider: vsphere
    image_ovf_path: "/images/kubeoperator_centos_7.6.1810/kubeoperator_centos_7.6.1810.ovf"
    image_vmdk_path: "/images/kubeoperator_centos_7.6.1810/kubeoperator_centos_7.6.1810-1.vmdk"
    image_name: "kubeoperator_centos_7.6.1810"
zone:
  network:
    configs:
      - name: vc_network
        alias: 网络适配器
        value: ""
        type: Select
        option_var: "networks"
      - name: vc_ip_start
        alias: 起始IP
        value: ""
        type: Input
      - name: vc_ip_end
        alias: 终止IP
        value: ""
        type: Input
      - name: vc_gateway
        alias: 网关地址
        value: ""
        type: Input
  storage:
    configs:
      - name: vc_storage
        alias: 存储器
        value: ""
        type: Select
        option_var: "storages"
plan:
  configs:
    - name: k8s_deploy_model
      type: Select
      alias: 部署模型
      options:
        - name: 一主多节点
          value: single
  infra:
    - name: k8s_master_model
      alias: Master 规格
    - name: k8s_worker_model
      alias: Worker 规格
    - name: k8s_daemon_model
      alias: Daemon 规格
  models:
    - name: small
      meta:
        cpu: 2
        memory: 8
        disk: 100
    - name: medium
      meta:
        cpu: 4
        memory: 16
        disk: 100
    - name: large
      meta:
        cpu: 8
        memory: 32
        disk: 100
    - name: xlarge
      meta:
        cpu: 16
        memory: 64
        disk: 100
    - name: 2xlarge
      meta:
        cpu: 32
        memory: 128
        disk: 100
    - name: 4xlarge
      meta:
        cpu: 64
        memory: 256
        disk: 100





