name: Vshpere
region:
  vars:
    provider: vsphere
    image_ovf_path: "/images/kubeoperator_centos_7.6.1810/kubeoperator_centos_7.6.1810.ovf"
    image_vmdk_path: "/images/kubeoperator_centos_7.6.1810/kubeoperator_centos_7.6.1810-1.vmdk"
    image_name: "kubeoperator_centos_7.6.1810"
plan:
  infra:
    - name: k8s_master_model
      alias: Master 规格
    - name: k8s_worker_model
      alias: Worker 规格
  models:
    - name: small
      meta:
        cpu: 2
        memory: 8
        disk: 100
    - name: medium
      meta:
        cpu: 4
        memory: 16
        disk: 100
    - name: large
      meta:
        cpu: 8
        memory: 32
        disk: 100
    - name: xlarge
      meta:
        cpu: 16
        memory: 64
        disk: 100
    - name: 2xlarge
      meta:
        cpu: 32
        memory: 128
        disk: 100
    - name: 4xlarge
      meta:
        cpu: 64
        memory: 256
        disk: 100
