name: Vshpere
region:
  configs:
    - name: vc_host
      alias: vCenter Host
      value: vcenter-example.com
      type: Input

    - name: vc_port
      alias: vCenter Port
      value: 443
      type: Input

    - name: vc_username
      alias: vCenter 用户名
      value: administrator@vsphere.local
      type: Input

    - name: vc_password
      alias: vCenter 密码
      value: xxxxxxxx
      type: Password
  vars:
    provider: vsphere
zone:
  network:
    configs:
      - name: vc_network
        alias: 网络适配器
        value: ""
        type: Select
        option_var: "networks"
      - name: vc_ip_start
        alias: 起始IP
        value: ""
        type: Input
      - name: vc_ip_end
        alias: 终止IP
        value: ""
        type: Input
      - name: vc_gateway
        alias: 网关地址
        value: ""
        type: Input
  image:
    configs:
      - name: vc_image
        alias: 镜像
        option_var: "images"
        value: ""
        type: Select
  storage:
    configs:
      - name: vc_storage
        alias: 存储器
        value: ""
        type: Select
        option_var: "storages"
  others:
    configs:
      - name: vc_folder
        alias: VM文件夹
        value: kubeops
        type: Input
plan:
  configs:
    - name: k8s_deploy_model
      type: Select
      alias: 部署模型
      options:
        - name: 一主多节点
          value: single
        - name: 多主多节点
          value: multiple
  infra:
    - name: k8s_master_model
      alias: Master 规格
    - name: k8s_worker_model
      alias: Worker 规格
    - name: k8s_daemon_model
      alias: Daemon 规格
  models:
    - name: small
      meta:
        cpu: 2
        memory: 8
        disk: 100
    - name: medium
      meta:
        cpu: 4
        memory: 16
        disk: 100
    - name: large
      meta:
        cpu: 8
        memory: 32
        disk: 100
    - name: xlarge
      meta:
        cpu: 16
        memory: 64
        disk: 100
    - name: 2xlarge
      meta:
        cpu: 32
        memory: 128
        disk: 100
    - name: 4xlarge
      meta:
        cpu: 64
        memory: 256
        disk: 100





