- name: Add specfic DNS into /etc/resolv.conf
  shell: grep {{ lookup('env','REGISTORY_HOSTNAME') }} /etc/resolv.conf || echo "nameserver {{ lookup('env','REGISTORY_HOSTNAME') }}" >> /etc/resolv.conf

