name: LDAP/AD
config:
  name: ldap_auth
  challenge: 'true'
  login: 'true'
  kind: LDAPPasswordIdentityProvider
  attributes:
    id:
      - dn
    email:
      - mail
    name:
      - cn
    preferredUsername:
      - uid
  insecure: 'false'
options:
  - name: url
    default: ldap://ldap.example.com:389/ou=users,dc=example,dc=com?uid
    type: text
  - name: bindDN
    default: ''
    type: text
  - name: bindPassword
    default:
    type: text
vars:
  - name: openshift_master_ldap_ca
    default: ca-content
    type: textarea