resource: kubernetes-dbaas
version: 1.13.5
enable_auth: []
operations:
  - name: install
    display_on:
      - "READY"
      - "ERROR"
    comment: "安装"
    icon: random
    event: "install"
    redirect: "deploy"
  - name: uninstall
    display_on:
      - "RUNNING"
      - "ERROR"
    comment: "卸载"
    icon: trash
    event: "uninstall"
    redirect: "deploy"

  - name: node
    comment: "管理节点"
    redirect: "node"
    icon: linode
playbooks:
  - name:  common-config
    alias: common/common.yml
  - name:  install-k8s
    alias: kubeasz/90.setup.yml
  - name:  uninstall-k8s
    alias: kubeasz/99.clean.yml
roles:
  - name: config
    children:
      - kubeasz
  - name: cluster_nodes
    children:
      - master
      - worker
  - name: all_nodes
    children:
      - lb
      - daemon
      - cluster_nodes
  - name: kube-node
    children:
      - worker
  - name: kube-master
    children:
      - master
  - name: etcd
    children:
      - master
    meta:
      hidden: true
  - name: kubeasz
    children:
      - master
      - worker
      - daemon
      - lb
    meta:
      hidden: true
    vars:
      bin_dir: "/usr/local/bin"
      ca_dir: "/etc/kubernetes/ssl"
      CONTAINER_RUNTIME: "docker"
      CLUSTER_NETWORK: "flannel"
      SERVICE_CIDR: "10.68.0.0/16"
      CLUSTER_CIDR: "172.20.0.0/16"
      NODE_PORT_RANGE: "20000-40000"
      CLUSTER_KUBERNETES_SVC_IP: "10.68.0.1"
      CLUSTER_DNS_SVC_IP: "10.68.0.2"
      CLUSTER_DNS_DOMAIN: "cluster.local."
      #kubeOperator
      base_dir: "/opt/kubeOperator-kube-bin/1.13.5"
      kube_version: "1.13.5"
      repo_port: 8082
      registry_prefix: "registry.kubeops.io:8092"
      #dns
      dns_install: true
      dns_image: "docker.io/coredns/coredns"
      dns_version: "1.5.0"
      #metrics-server
      metricsserver_install: false
      metricsserver_image: "k8s.gcr.io/metrics-server-amd64"
      metricsserver_version: "v0.3.2"
      #dashboard
      dashboard_install: true
      dashboard_image: "k8s.gcr.io/kubernetes-dashboard-amd64"
      dashboard_version: "v1.10.0"
      #heapster
      heapster_install: true
      heapster_version: "v1.5.4"
      heapster_image: "gcr.io/google_containers/heapster-amd64"
      #traefik
      traefik_version: "v1.7.11"
      traefik_image: "docker.io/traefik"
      #efk
      efk_install: false
      #helm
      helm_namespace: kube-system
      helm_cert_cn: helm001
      tiller_sa: tiller
      tiller_cert_cn: tiller001
      tiller_image: "gcr.io/kubernetes-helm/tiller"
      tiller_version: "v2.12.3"
      #flannel
      NODE_WITH_MULTIPLE_NETWORKS: "true"
      FLANNEL_BACKEND: "vxlan"
      flanneld_image: "quay.io/coreos/flannel"
      flanneld_version: "v0.11.0-amd64"
      #registry
      REGISTRY_ACCOUNT_NAME: admin
      REGISTRY_ACCOUNT_PASSWORD: Calong@2015
      IMAGE_PULL_SECRET: registry-fit2cloud-com-key



templates:
  - name: 一主多节点
    comment: '此部署模型为一主多节点部署模型，1个daemon 节点,1个 Master 节点和至少3个 Worker 节点。'
    private_vars:
      DEPLOY_MODE: 'single-master'
      prometheus_install: false
      grafana_install: false
    private_config:
      - name: MASTER_IP
        alias: 域名
        type: Input
        default: master-1.$cluster_name$domain_suffix
        required: true
        help_text: kubernetes 访问地址
        display: true
      - name: KUBE_APISERVER
        alias: api-server 地址
        type: Input
        default: https://master-1.$cluster_name$domain_suffix:6443
        required: true
        help_text: kubernetes api-server 地址
        display: true
    operations:
      - name: install
        status_change:
          succeed: 'RUNNING'
          "on": 'INSTALLING'
          failed: 'ERROR'
        playbooks:
          - common-config
          - install-k8s
      - name: uninstall
        status_change:
          succeed: 'READY'
          "on": 'DELETING'
          failed: 'ERROR'
        playbooks:
          - uninstall-k8s
    roles:
      - name: master
        vars:
        meta:
          hidden: false
          allow_os:
            - name: CentOS
              version:
                - "7.6"
          node_vars: []
          requires:
            nodes_require:
              - '='
              - 1
            volumes_require:
              - name: "system"
                verbose: "系统卷:"
                minimal: 50
                excellent: 100
                comment: "系统卷，用于运行操作系统"
                unit: "GB"
            device_require:
              - name: "cpu_core"
                verbose: "CPU 核心数"
                minimal: 4
                excellent: 8
                comment: "无"
                unit: "个"
              - name: "memory_size"
                verbose: "内存大小"
                minimal: 8
                excellent: 16
                unit: "GB"
                comment: "无"
      - name: daemon
        vars:
        meta:
          hidden: false
          allow_os:
            - name: CentOS
              version:
                - "7.6"
          node_vars: []
          requires:
            nodes_require:
              - '='
              - 1
            volumes_require:
              - name: "system"
                verbose: "系统卷:"
                minimal: 50
                excellent: 100
                comment: "系统卷，用于运行操作系统"
                unit: "GB"
            device_require:
              - name: "cpu_core"
                verbose: "CPU 核心数"
                minimal: 2
                excellent: 4
                comment: "无"
                unit: "个"
              - name: "memory_size"
                verbose: "内存大小"
                minimal: 4
                excellent: 8
                unit: "GB"
                comment: "无"
      - name: worker
        vars:
        meta:
          hidden: false
          allow_os:
            - name: CentOS
              version:
                - "7.6"
          node_vars: []
          requires:
            nodes_require:
              - '>'
              - 3
            volumes_require:
              - name: "system"
                verbose: "系统卷:"
                minimal: 50
                excellent: 100
                comment: "系统卷，用于运行操作系统"
                unit: "GB"
            device_require:
              - name: "cpu_core"
                verbose: "CPU 核心数"
                minimal: 4
                excellent: 8
                comment: "无"
                unit: "个"
              - name: "memory_size"
                verbose: "内存大小"
                minimal: 16
                excellent: 32
                unit: "GB"
                comment: "无"
  - name: 多主多节点
    comment: '此部署模型为一主多节点部署模型，包括1个 load balance 节点，1个daemon 节点,3个 Master 节点和至少3个 worker 计算节点。'
    private_vars:
      DEPLOY_MODE: 'multi-master'
      prometheus_install: false
      grafana_install: false
    private_config:
      - name: MASTER_IP
        alias: 域名
        type: Input
        default: lb-1.$cluster_name$domain_suffix
        required: true
        help_text: kubernetes 访问地址
        display: true
      - name: KUBE_APISERVER
        alias: api-server 地址
        type: Input
        default: https://lb-1.$cluster_name$domain_suffix:6443
        required: true
        help_text: kubernetes api-server 地址
        display: true
    operations:
      - name: install
        status_change:
          succeed: 'RUNNING'
          "on": 'INSTALLING'
          failed: 'ERROR'
        playbooks:
          - common-config
          - install-k8s
      - name: uninstall
        status_change:
          succeed: 'READY'
          "on": 'DELETING'
          failed: 'ERROR'
        playbooks:
          - uninstall-k8s
    roles:
      - name: daemon
        vars:
        meta:
          hidden: false
          allow_os:
            - name: CentOS
              version:
                - "7.6"
          node_vars: []
          requires:
            nodes_require:
              - '='
              - 1
            volumes_require:
              - name: "system"
                verbose: "系统卷:"
                minimal: 50
                excellent: 100
                comment: "系统卷，用于运行操作系统"
                unit: "GB"
            device_require:
              - name: "cpu_core"
                verbose: "CPU 核心数"
                minimal: 2
                excellent: 4
                comment: "无"
                unit: "个"
              - name: "memory_size"
                verbose: "内存大小"
                minimal: 4
                excellent: 8
                unit: "GB"
                comment: "无"
      - name: lb
        vars:
          LB_ROLE: backup
        meta:
          hidden: false
          allow_os:
            - name: CentOS
              version:
                - "7.6"
          requires:
            nodes_require:
              - '='
              - 1
            volumes_require:
              - name: "system"
                verbose: "系统卷:"
                minimal: 50
                excellent: 100
                comment: "系统卷，用于运行操作系统"
                unit: "GB"
            device_require:
              - name: "cpu_core"
                verbose: "CPU 核心数"
                minimal: 2
                excellent: 4
                comment: "无"
                unit: "个"
              - name: "memory_size"
                verbose: "内存大小"
                minimal: 4
                excellent: 8
                unit: "GB"
                comment: "无"

      - name: master
        meta:
          hidden: false
          allow_os:
            - name: CentOS
              version:
                - "7.6"
          node_vars: []
          requires:
            nodes_require:
              - '='
              - 3
            volumes_require:
              - name: "system"
                verbose: "系统卷:"
                minimal: 50
                excellent: 100
                comment: "系统卷，用于运行操作系统"
                unit: "GB"
            device_require:
              - name: "cpu_core"
                verbose: "CPU 核心数"
                minimal: 4
                excellent: 8
                comment: "无"
                unit: "个"
              - name: "memory_size"
                verbose: "内存大小"
                minimal: 8
                excellent: 16
                unit: "GB"
                comment: "无"
      - name: worker
        vars:
        meta:
          hidden: false
          allow_os:
            - name: CentOS
              version:
                - "7.6"
          node_vars: []
          requires:
            nodes_require:
              - '>'
              - 3
            volumes_require:
              - name: "system"
                verbose: "系统卷:"
                minimal: 50
                excellent: 100
                comment: "系统卷，用于运行操作系统"
                unit: "GB"
            device_require:
              - name: "cpu_core"
                verbose: "CPU 核心数"
                minimal: 4
                excellent: 8
                comment: "无"
                unit: "个"
              - name: "memory_size"
                verbose: "内存大小"
                minimal: 16
                excellent: 32
                unit: "GB"
                comment: "无"

