name: glusterfs
roles:
  - name: glusterfs
    meta:
      requires:
        - '>'
        - 3
vars:
  openshift_storage_glusterfs_namespace: app-storage
  openshift_storage_glusterfs_storageclass: true
  openshift_storage_glusterfs_storageclass_default: true
  openshift_storage_glusterfs_block_storageclass: true
  openshift_storage_glusterfs_block_storageclass_default: false
  openshift_storage_glusterfs_is_native: false
  openshift_storage_glusterfs_heketi_is_native: true
  openshift_storage_glusterfs_heketi_executor: ssh
  openshift_storage_glusterfs_heketi_ssh_keyfile: /root/.ssh/id_rsa
  openshift_storage_glusterfs_wipe: true
options: {}
operations:
  install:
    playbooks:
      - config-glusterfs
  uninstall:
    playbooks:
      - uninstall-glusterfs
health_check:
  playbooks:
    - name: ''




