app:
  secret: fLgapPkmCaDxkJvC
  session:
    max: 999
bind:
  host: 0.0.0.0
  port: 8080
db:
  host: 127.0.0.1
  port: 3307
  user: root
  password: 123456
  name: ko
redis:
  host: 127.0.0.1
  port: 6379
  db: 0
logging:
  level: debug
