DEBUG: true
DB_HOST: localhost
DB_PORT: 3306
DB_NAME: kubeoperator
DB_USER: root
DB_PASSWORD: Calong@2015
REDIS_HOST: localhost
REDIS_PORT: 6379
REDIS_PASSWORD:
ELASTICSEARCH_HOST: localhost
ELASTICSEARCH_PORT: 9200
SECRET_KEY: "33h+(k@zm7o#@j%7_1(8q8dlzn9%5ajml2_frgp5e2ikxzfw$8"