DEBUG: false
#DB_HOST: localhost
DB_HOST: 172.16.10.185
DB_PORT: 3306
DB_NAME: kube-operator
DB_USER: root
#DB_PASSWORD: 1234
DB_PASSWORD: SuMk2lH20ocmvyu1p38m40
REDIS_HOST: 127.0.0.1
REDIS_PORT: 6379
REDIS_PASSWORD:
SECRET_KEY: "33h+(k@zm7o#@j%7_1(8q8dlzn9%5ajml2_frgp5e2ikxzfw$8"
ELASTICSEARCH_HOST: 127.0.0.1
ELASTICSEARCH_PORT: 9200