DEBUG: true
DB_HOST: 172.16.10.142
DB_PORT: 3306
DB_NAME: kube-operator
DB_USER: root
DB_PASSWORD: SuMk2lH20ocmvyu1p38m40
REDIS_HOST: 172.16.10.142
REDIS_PORT: 6379
REDIS_PASSWORD:
ELASTICSEARCH_HOST: 172.16.10.142
ELASTICSEARCH_PORT: 9200
SECRET_KEY: "33h+(k@zm7o#@j%7_1(8q8dlzn9%5ajml2_frgp5e2ikxzfw$8"