- name: deploy prometheus operator
  shell: "{{ bin_dir }}/helm upgrade  fit2cloud-prometheus-operator --namespace fit2cloud \
      --install --force --recreate-pods \
      --set storage.storageClassName={{ STORAGE_CLASS_NAME }} \
      --set storage.prometheus.capacity={{ PROMETHEUS_CAPACITY }} \
      --set modules.imagePullSecret={{ IMAGE_PULL_SECRET }} \
      --set modules.imagePrefix={{MASTER_IP}}:30003/ \
      /tmp/fit2cloud-prometheus-operator-2.0-dev-latest.tgz"
  ignore_errors: true

- name: deploy dbaas-rds
  shell: "{{ bin_dir }}/helm upgrade fit2cloud-dbaas-rds-operator --namespace fit2cloud \
      --install --force --recreate-pods \
      --set modules.imagePullSecret={{ IMAGE_PULL_SECRET }} \
      --set modules.imagePullPolicy=Always \
      --set modules.imagePrefix={{MASTER_IP}}:30003/ \
      --set modules.imageTag=dev \
      /tmp/fit2cloud-dbaas-rds-operator-2.0-dev-latest.tgz"
  ignore_errors: true

- name: deploy cmp
  shell: "{{ bin_dir }}/helm upgrade fit2cloud-cmp-deployment --namespace fit2cloud \
      --install --force --recreate-pods \
      --set storage.storageClassName={{ STORAGE_CLASS_NAME }} \
      --set storage.elasticsearch.capacity={{ CMP_ELASTICSEARCH_CAPACITY }} \
      --set storage.logs.capacity={{ CMP_LOGS_CAPACITY }} \
      --set storage.mysql.capacity={{ CMP_MYSQL_CAPACITY }} \
      --set storage.prometheus.capacity={{ CMP_PROMETHEUS_CAPACITY }} \
      --set storage.redis.capacity={{ CMP_REDIS_CAPACITY }} \
      --set storage.shareFiles.capacity={{ CMP_SHAREFILES_CAPACITY }} \
      --set modules.imagePullSecret={{ IMAGE_PULL_SECRET }} \
      --set modules.imagePullPolicy=Always \
      --set modules.imagePrefix={{MASTER_IP}}:30003/ \
      --set modules.imageTag=master \
      --set modules.keycloak.runMode=test \
      --set cmp.logLevel=master \
      --set cmp.gatewayHost={{ CMP_GATEWAY_HOST }} \
      /tmp/fit2cloud-cmp-deployment-2.0-dev-latest.tgz"
  ignore_errors: true