- block:
    - name: 在deploy 节点创建相关目录
      file: path={{ item }} state=directory
      with_items:
        - /opt/kube/kube-system/coredns

    - name: 准备 DNS的部署文件
      template: src=1.15/{{ item }}.yaml.j2 dest=/opt/kube/kube-system/coredns/{{ item }}.yaml
      with_items:
        - coredns
        - autoscaler

    - name: 获取所有已经创建的POD信息
      command: "{{ bin_dir }}/kubectl get pod --all-namespaces"
      register: pod_info
  delegate_to: "{{ groups['kube-master'][0] }}"
  run_once: true

- block:
    - name: 创建CoreDNS部署
      shell: "{{ bin_dir }}/kubectl apply -f /opt/kube/kube-system/coredns"
      run_once: true
      delegate_to: "{{ groups['kube-master'][0] }}"
  when:
    - '"coredns" not in pod_info.stdout'
    - 'dns_install'
  ignore_errors: true
