- block:
    - name: 在 deploy节点创建相关目录
      file: path=/opt/kube/kube-system/coredns state=directory

    - name: 准备 DNS的部署文件
      template: src=coredns.yaml.j2 dest=/opt/kube/kube-system/coredns/coredns.yaml

    - name: 获取所有已经创建的POD信息
      command: "{{ bin_dir }}/kubectl get pod --all-namespaces"
      register: pod_info
  delegate_to: "{{ groups['kube-master'][0] }}"
  run_once: true

- block:
    - name: 创建 CoreDNS部署
      shell: "{{ bin_dir }}/kubectl apply -f /opt/kube/kube-system/coredns/coredns.yaml"
      run_once: true
      delegate_to: "{{ groups['kube-master'][0] }}"
  when:
    - '"coredns" not in pod_info.stdout'
    - 'dns_install'
  ignore_errors: true
