- name: 解锁 resolv.conf
  shell: "chattr -i /etc/resolv.conf"

- name: 更新 resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

- name: 锁定 resolv.conf
  shell: "chattr +i /etc/resolv.conf"

- name: 重新启动firewall
  service:
    name: firewalld
    state: restarted