- name: 分发 ssh key
  authorized_key:
    user: root
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
    state: present
    exclusive: no

- name: 忽略 ssh 登陆 key 校验
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^UseDNS.*'
    line: UseDNS no
  notify:
    - restart sshd


- name: 创建仓库备份目录
  file:
    path: /etc/yum.repos.d/bak
    state: directory

- name: 备份原仓库
  shell: "mv -f /etc/yum.repos.d/*.repo /etc/yum.repos.d/bak >/dev/null 2>&1  || ls /etc/yum.repos.d/ >/dev/null 2>&1"

- name: 删除其他仓库
  file:
    path: /etc/yum.repos.d/*
    state: absent

- name: 添加离线仓库
  template:
    src: templates/kubeops.repo.j2
    dest: /etc/yum.repos.d/kubeops.repo

- name: make yum cache
  shell: yum makecache
  ignore_errors: true

- name: 安装基础软件包
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{packages}}"

- name: 开启firewalld 防火墙
  service:
    name: firewalld
    state: started
    enabled: true

- name: 打开防火墙UDP端口
  firewalld:
    port: "{{item}}/udp"
    permanent: true
    state: enabled
  with_items: "{{firewall_udp_ports}}"

- name: 打开防火墙TCP端口
  firewalld:
    port: "{{item}}/tcp"
    permanent: true
    state: enabled
  with_items: "{{firewall_tcp_ports}}"

- name: 生效防火墙配置
  shell: "firewall-cmd --reload"

- name: 配置主机名
  hostname:
    name: "{{inventory_hostname}}"
