alertmanager:
  persistentVolume:
    enabled: true
  service:
    type: ClusterIP

server:
  persistentVolume:
    enabled: true
  service:
    type: NodePort

pushgateway:
  enabled: false

kubeStateMetrics:
  image:
    repository: registry.kubeops.io:8092/quay.io/coreos/kube-state-metrics
