- name:  生成 https 证书
  shell: "openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj \"/CN={{APP_DOMAIN}}\""
  args:
    chdir: "/tmp/"
  ignore_errors: true

- name: 生成 secret
  shell: kubectl -n kube-system create secret tls traefik-tls-cert --key=tls.key --cert=tls.crt
  args:
    chdir: "/tmp/"
  ignore_errors: true

- name: 生成 ingress 部署文件
  template:
    src: traefik/traefik-ingress.yaml.j2
    dest: "{{ base_dir }}/manifests/ingress/traefik/traefik-ingress.yaml"
  when: "kube_version_main  == '1.15'"

- name: 生成 ingress 部署文件
  template:
    src: traefik/traefik-ingress.yaml.1.16.j2
    dest: "{{ base_dir }}/manifests/ingress/traefik/traefik-ingress.yaml"
  when: "kube_version_main  == '1.16'"

- name: 创建 traefik部署
  shell: "{{ bin_dir }}/kubectl apply -f {{ base_dir }}/manifests/ingress/traefik/traefik-ingress.yaml"
  delegate_to: "{{ groups['kube-master'][0] }}"
  run_once: true
