name: Vshpere
meta:
  configs:
    - name: vc_host
      alias: vCenter Host
      value: vcenter-example.com
      type: Input

    - name: vc_username
      alias: vCenter 用户名
      value: administrator@vsphere.local
      type: Input

    - name: vc_password
      alias: vCenter 密码
      value: xxxxxxxx
      type: Password
  vars:
    provider: vsphere



