- name: Install dnsmasq
  yum:
    name: "dnsmasq"

- name: Restart services
  service:
    state: restarted
    name: "{{ item }}"
  with_items:
    - dbus
    - dnsmasq
    - NetworkManager
    - systemd-logind
    - systemd-hostnamed