- hosts: f2o
  tasks:
    - name: SSH do not use dns lookup
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^UseDNS.*'
        line: UseDNS no
      notify:
        - restart sshd
  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted