- import_tasks: pull-images.yml
- import_tasks: prepare.yml


- name: create fit2cloud namespace
  shell: "{{ bin_dir }}/kubectl create ns fit2cloud"
  ignore_errors: true

- name: get registry secret
  command: "{{ bin_dir }}/kubectl get secrets -n fit2cloud"
  register: secrets_list

- name: delete registry secret
  shell: "{{ bin_dir }}/kubectl delete secrets {{ IMAGE_PULL_SECRET }} -n fit2cloud"
  when: '"{{ IMAGE_PULL_SECRET }}" in secrets_list.stdout'
  ignore_errors: true

- name: create registry secret
  shell: "{{ bin_dir }}/kubectl create secret docker-registry {{ IMAGE_PULL_SECRET }} \
        --namespace=fit2cloud \
        --docker-server={{MASTER_IP}}:30003 \
        --docker-username={{ REGISTRY_ACCOUNT_NAME }} \
        --docker-password={{ REGISTRY_ACCOUNT_PASSWORD }}

- name: copy helm chart
  copy: src={{ item }} dest=/tmp/{{ item }}
  with_items:
    - fit2cloud-cmp-deployment-2.0-dev-latest.tgz
    - fit2cloud-dbaas-rds-operator-2.0-dev-latest.tgz
    - fit2cloud-prometheus-operator-2.0-dev-latest.tgz

- name: get installed helm application
  command: "{{ bin_dir }}/helm list -a"
  register: helm_list

- name: delete prometheus operator
  shell: "{{ bin_dir }}/helm delete fit2cloud-prometheus-operator --purge"
  when: '"fit2cloud-prometheus-operator" in helm_list.stdout'
  ignore_errors: true

- name: delete dbaas-rds
  shell: "{{ bin_dir }}/helm delete fit2cloud-dbaas-rds-operator --purge"
  when: '"fit2cloud-dbaas-rds-operator" in helm_list.stdout'
  ignore_errors: true

- name: delete cmp
  shell: "{{ bin_dir }}/helm delete fit2cloud-cmp-deployment --purge"
  when: '"fit2cloud-cmp-deployment" in helm_list.stdout'
  ignore_errors: true

- name: wait for the pod deletion to complete
  shell: "{{ bin_dir }}/kubectl get pod -n fit2cloud -o wide|wc -l"
  register: pod_status
  until: pod_status.stdout == "0"
  delegate_to: "{{ groups.helm[0] }}"
  retries: 5
  delay: 10
  ignore_errors: true

- name: deploy prometheus operator
  shell: "{{ bin_dir }}/helm install --name fit2cloud-prometheus-operator --namespace fit2cloud \
      --set storage.storageClassName={{ STORAGE_CLASS_NAME }} \
      --set storage.prometheus.capacity={{ PROMETHEUS_CAPACITY }} \
      --set modules.imagePullSecret={{ IMAGE_PULL_SECRET }} \
      --set modules.imagePrefix={{MASTER_IP}}:30003/{{ REGISTRY_PROJECT_NAME }}/ \
      /tmp/fit2cloud-prometheus-operator-2.0-dev-latest.tgz"
  ignore_errors: true

- name: deploy dbaas-rds
  shell: "{{ bin_dir }}/helm install --name fit2cloud-dbaas-rds-operator --namespace fit2cloud \
      --set modules.imagePullSecret={{ IMAGE_PULL_SECRET }} \
      --set modules.imagePullPolicy=Always \
      --set modules.imagePrefix={{MASTER_IP}}:30003/{{ REGISTRY_PROJECT_NAME }}/ \
      --set modules.imageTag=dev \
      /tmp/fit2cloud-dbaas-rds-operator-2.0-dev-latest.tgz"
  ignore_errors: true

- name: deploy cmp
  shell: "{{ bin_dir }}/helm install --name fit2cloud-cmp-deployment --namespace fit2cloud \
      --set storage.storageClassName={{ STORAGE_CLASS_NAME }} \
      --set storage.elasticsearch.capacity={{ CMP_ELASTICSEARCH_CAPACITY }} \
      --set storage.logs.capacity={{ CMP_LOGS_CAPACITY }} \
      --set storage.mysql.capacity={{ CMP_MYSQL_CAPACITY }} \
      --set storage.prometheus.capacity={{ CMP_PROMETHEUS_CAPACITY }} \
      --set storage.redis.capacity={{ CMP_REDIS_CAPACITY }} \
      --set storage.shareFiles.capacity={{ CMP_SHAREFILES_CAPACITY }} \
      --set modules.imagePullSecret={{ IMAGE_PULL_SECRET }} \
      --set modules.imagePullPolicy=Always \
      --set modules.imagePrefix={{MASTER_IP}}:30003/{{ REGISTRY_PROJECT_NAME }}/ \
      --set modules.imageTag=master \
      --set modules.keycloak.runMode=test \
      --set cmp.logLevel=master \
      --set cmp.gatewayHost={{ CMP_GATEWAY_HOST }} \
      /tmp/fit2cloud-cmp-deployment-2.0-dev-latest.tgz"
  ignore_errors: true
