- name: copy  harbor projects script
  template: src=harbor.projects.sh.j2 dest=/tmp/harbor.projects.sh mode=0755

- name:  create harbor projects
  shell: "bash /tmp/harbor.projects.sh"

- name: copy cmp.sh
  template: src=fit2cloud-cmp.sh.j2 dest=/tmp/fit2cloud-cmp.sh mode=0755

- name: install cmp image
  shell: "bash /tmp/fit2cloud-cmp.sh"

- name: copy dbaas.sh file
  template: src=fit2cloud-dbaas.sh.j2 dest=/tmp/fit2cloud-dbaas.sh mode=0755

- name: install dbaas image
  shell: "bash /tmp/fit2cloud-dbaas.sh"

- name: copy prometheus.sh file
  template: src=fit2cloud-prometheus.sh.j2 dest=/tmp/fit2cloud-prometheus.sh mode=0755

- name: do shell | install prometheus image
  shell: "bash /tmp/fit2cloud-prometheus.sh"