apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: f2c-{{ template "kuberhealthy.name" . }}
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - namespaces
    - componentstatuses
    - nodes
    verbs:
    - get
    - list
    - watch
  
