definitions:
  serializer.CreatHostRequest:
    properties:
      credential_name:
        type: string
      ip:
        type: string
      name:
        type: string
      port:
        type: string
    type: object
info:
  contact:
    email: support@fit2cloud.com
    name: Fit2cloud Support
    url: https://www.fit2cloud.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://kubeoperator.io
  title: KubeOperator Restful API
  version: "1.0"
paths:
  /hosts/:
    post:
      consumes:
      - application/json
      description: Create a Host
      parameters:
      - description: create host request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/serializer.CreatHostRequest'
      produces:
      - application/json
      summary: Create a Host
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
