basePath: /api/v1
definitions:
  serializer.BatchRequest:
    properties:
      items:
        items:
          $ref: '#/definitions/serializer.Cluster'
        type: array
      operation:
        type: string
    type: object
  serializer.BatchResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/serializer.Cluster'
        type: array
    type: object
  serializer.Cluster:
    properties:
      name:
        type: string
      status:
        type: string
    type: object
  serializer.CreateRequest:
    properties:
      name:
        type: string
    type: object
  serializer.CreateResponse:
    properties:
      item:
        $ref: '#/definitions/serializer.Cluster'
        type: object
    type: object
  serializer.DeleteResponse:
    type: object
  serializer.GetResponse:
    properties:
      item:
        $ref: '#/definitions/serializer.Cluster'
        type: object
    type: object
  serializer.ListResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/serializer.Cluster'
        type: array
      total:
        type: integer
    type: object
  serializer.UpdateRequest:
    properties:
      name:
        type: string
    type: object
  serializer.UpdateResponse:
    properties:
      item:
        $ref: '#/definitions/serializer.Cluster'
        type: object
    type: object
host: localhost:8080
info:
  contact:
    email: support@fit2cloud.com
    name: Fit2cloud Support
    url: https://www.fit2cloud.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://kubeoperator.io
  title: KubeOperator Restful API
paths:
  /clusters/:
    get:
      consumes:
      - application/json
      description: List clusters
      parameters:
      - description: page num
        in: query
        name: pageNum
        type: string
      - description: page size
        in: query
        name: pageSize
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.ListResponse'
      summary: Cluster
    post:
      consumes:
      - application/json
      description: Create a Cluster
      parameters:
      - description: cluster
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/serializer.CreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/serializer.CreateResponse'
      summary: Cluster
  /clusters/{cluster_name}:
    delete:
      consumes:
      - application/json
      description: Delete a Cluster
      parameters:
      - description: cluster name
        in: path
        name: cluster_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.DeleteResponse'
      summary: Cluster
    get:
      consumes:
      - application/json
      description: Get Cluster
      parameters:
      - description: cluster name
        in: path
        name: cluster_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.GetResponse'
      summary: Cluster
    patch:
      consumes:
      - application/json
      description: Update a Cluster
      parameters:
      - description: cluster
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/serializer.UpdateRequest'
      - description: cluster name
        in: path
        name: cluster_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.UpdateResponse'
      summary: Cluster
  /clusters/batch/:
    post:
      consumes:
      - application/json
      description: Batch Clusters
      parameters:
      - description: Batch
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/serializer.BatchRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.BatchResponse'
      summary: Cluster
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
