basePath: /api/v1
definitions:
  serializer.Cluster:
    properties:
      name:
        type: string
      status:
        type: string
    type: object
  serializer.ListResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/serializer.Cluster'
        type: array
    type: object
  serializer.PageResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/serializer.Cluster'
        type: array
      total:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: support@fit2cloud.com
    name: Fit2cloud Support
    url: https://www.fit2cloud.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://kubeoperator.io
  title: KubeOperator Restful API
paths:
  /clusters/:
    get:
      consumes:
      - application/json
      description: List all clusters
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.ListResponse'
      summary: Cluster
  /clusters/page/:
    get:
      consumes:
      - application/json
      description: List all clusters with page
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.PageResponse'
      summary: Cluster
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
