http_ingress:
  registry:
    name: f2c-registry-ui-ingress
    namespace: kube-system
  traefik:
    name: f2c-traefik-ingress
    namespace: kube-system
  grafana:
    name: f2c-grafana
    namespace: monitoring
  prometheus:
    name: f2c-prometheus-server
    namespace: monitoring

https_ingress:
  dashboard:
    name: f2c-dashboard-ingress
    namespace: kube-system
  weave:
    name: f2c-weave-ingress
    namespace: weave

