alertmanager:
  persistentVolume:
    enabled: true
  service:
    type: NodePort
    nodePort: 39001

server:
  persistentVolume:
    enabled: true
  service:
    type: NodePort
    nodePort: 39000

pushgateway:
  enabled: false

kubeStateMetrics:
  image:
    repository: registry.kubeops.io:8092/quay.io/coreos/kube-state-metrics
