- block:
    - name: 安装 rsync
      package: name=rsync state=present

    - name: 复制 manifests至 deploy节点
      synchronize: src=manifests dest={{ base_dir }}

    - name: 推送 ssh 密钥对至 deploy节点
      copy: src=~/.ssh/{{ item }} dest=~/.ssh/{{ item }} mode=0600
      with_items:
      - id_rsa
      - id_rsa.pub
  run_once: true
  when: "ansible_env['SSH_CLIENT'].split(' ')[0] != inventory_hostname"